### ISSUE TITLE
Doesn't work with nextcloud 25.0.1

### ISSUE THREAD

**Issue by hax4dazy** [skjnldsv/pride#11]
Seems like something might have broken it. Reinstalling didn't do anything to get the bar back. Also it seems like this nextcloud update was a big one and made a lot of UI changes

**Comment by igklein** [comment]
I really like this app and would be grateful if it could be updated to work on 25.x.x

**Comment by skjnldsv** [comment]
The design changed too much for 25. What do you think of this?
Is it ok to enforce the yellow `#E4D56F` as admin primary? What do you think? :wink: 

![dev skjnldsv com_settings_user_theming](https://user-images.githubusercontent.com/14975046/205307512-11d336d4-2f86-4459-a5c9-e5befc5a39b8.png)

**Comment by skjnldsv** [comment]
Unfortunately, for 25, it will prevent any theme change.
Meaning it will be enforced for all users.

For 26, it will just be enforced as the admin default (like the screenshot above), and any user will be able to pick another one if necessary

**Comment by hax4dazy** [comment]
Could you maybe add some toggle that would make them theme enforced for all users? That way admins can choose if they want to enforce the theme or not.

**Comment by skjnldsv** [comment]
> Could you maybe add some toggle that would make them theme enforced for all users? That way admins can choose if they want to enforce the theme or not.

You can already disable user theming:
![image](https://user-images.githubusercontent.com/14975046/205312987-5aa061fc-eb7b-452b-af3b-47eea70735fc.png)

**Comment by skjnldsv** [comment]
So, good for everyone? :)

![localhost_8080_index php_login_redirect_url=_index php_apps_files_](https://user-images.githubusercontent.com/14975046/205313360-0c14641c-c7a5-4026-9491-83d37d965552.png)

**Comment by hax4dazy** [comment]
Thanks ❤️

**Comment by skjnldsv** [comment]
Released! :rainbow:
