### ISSUE TITLE
don't work on https://edudocs.de/heinereal/

### ISSUE THREAD

**Issue by BienenAnnie** [skjnldsv/pride#33]
<img width="1440" alt="Screenshot 2023-08-06 at 14 26 55" src="https://github.com/skjnldsv/pride/assets/97355676/b7ae5cd6-178b-4811-b28e-7e4f0a5bf797">
<img width="1440" alt="Screenshot 2023-08-06 at 14 25 42" src="https://github.com/skjnldsv/pride/assets/97355676/aac4a64a-8a94-4d62-9ac6-d588f70f7d0e">
<img width="1440" alt="Screenshot 2023-08-06 at 14 25 27" src="https://github.com/skjnldsv/pride/assets/97355676/c5da67a6-8827-46cf-8ce3-3ff08fa23b73">

**Comment by skjnldsv** [comment]
Can you show your user theming settings? :)

**Comment by BienenAnnie** [comment]
Yes sure:
<img width="1440" alt="Screenshot 2023-08-06 at 19 03 14" src="https://github.com/skjnldsv/pride/assets/97355676/ecaa7d9e-c9d3-4ceb-af5e-7964a7c717ed">
<img width="1440" alt="Screenshot 2023-08-06 at 19 03 04" src="https://github.com/skjnldsv/pride/assets/97355676/4f7eb6c0-0c53-4ad7-a60a-a3d7a8811cd1">
<img width="1440" alt="Screenshot 2023-08-06 at 19 02 23" src="https://github.com/skjnldsv/pride/assets/97355676/300a1210-68f6-4335-84a3-cf8ed1227299">

**Comment by BienenAnnie** [comment]
It is also not possible to chance the colour. So it's E4D56F Yellow now and I can't do anything against it.

**Comment by BienenAnnie** [comment]
<img width="1440" alt="Screenshot 2023-08-06 at 19 07 36" src="https://github.com/skjnldsv/pride/assets/97355676/1ec7612a-5461-434c-b24c-c6372b7f8319">

**Comment by BienenAnnie** [comment]
Maybe this is helpful too?
<img width="1440" alt="Screenshot 2023-08-06 at 19 09 25" src="https://github.com/skjnldsv/pride/assets/97355676/39c1ec8a-6e88-47b8-9244-c9ecd2a3c196">

**Comment by skjnldsv** [comment]
Thanks!
You have removed the background in your admin settings.
Click the restore setting button:
![image](https://github.com/skjnldsv/pride/assets/14975046/60cf6350-cf21-4b62-b326-82e024e3d9ca)
