### ISSUE TITLE
Toggle in Personal Settings

### ISSUE THREAD

**Issue by gary-kim** [skjnldsv/pride#5]
I'd like to have this on my instance but the instance is used by more than just me.

There could be a toggle in personal settings so users can choose on their own?

**Comment by skjnldsv** [comment]
Could be nice yes :p
Unfortunately, this is of course far from my current priorities :(

**Comment by skjnldsv** [comment]
Might be easier to do that in 25 :thinking:

**Comment by skjnldsv** [comment]
Fixed for 26
