### ISSUE TITLE
Certificate "4346" has been revoked 

### ISSUE THREAD

**Issue by gryffyn** [skjnldsv/pride#6]
Upon trying to install this app from the nextcloud store, nextcloud just says `Certificate "4346" has been revoked`.

Thanks

**Comment by skjnldsv** [comment]
Fixed with https://github.com/skjnldsv/pride/releases/tag/0.0.4

**Comment by skjnldsv** [comment]
Ah nope, certificate still revoked :thinking: 
@rullzer, I used the new crt from https://github.com/nextcloud/server/issues/20674

**Comment by skjnldsv** [comment]
Ah, I needed to re-register, fixed!
